version: '2'
services:
  frontend:
    build: src/front/
    depends_on:
     - backend
  backend:
    build: src/
    ports:
     - "80:8080"
    volumes:
     - .:/code
    depends_on:
     - redis
  redis:
    image: redis
